### PR TITLE
import limit to number of messages per phone for a day

### PR DESCRIPTION
**Pull request by grahamegrieve**

### CODE REVIEW

**Comment by vadi2** [comment]
It looks like the line endings changed on a few files

**Comment by grahamegrieve** [comment]
What is with the line endings anyway? Why is VS always bitching about them? it's not like I ever do anything to them

**Comment by vadi2** [comment]
It's standard to keep the repo in UNIX line endings and for Git to auto-convert to Windows ones when it's downloading the files. Maybe your Git isn't setup to auto-convert, and VS isn't happy they're in Windows style?

**Comment by grahamegrieve** [comment]
my git is set to not change line endings - no, I don't want git interfering ... It's bizarre that it's a system wide setting

**Comment by vadi2** [comment]
It makes things a lot better - I can recommend turning it on so we forget about these line ending troubles - this way VS will be happy and all other tools too. https://github.com/grahamegrieve/ClinicArrivals/pull/40 will enable it for the repo

**Comment by vadi2** [comment]
Git is set not to interfere so VS is interfering and changing them, hence why we have an entire file 'changed' in this PR

**Pull request merged**
